version: '3'

services:
  s1:
    build: .
    volumes:
      # Local app folder is mounted to the container
      - .:/usr/src/app
      # node_modules that are installed inside the container during
      # the build will not be overridden by your current folder.
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
      - "9229:9229"
    command:
      - npm
      - start